season_1_urls = ['https://arresteddevelopment.fandom.com/wiki/Transcript_of_Pilot',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Top_Banana',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Bringing_Up_Buster',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Key_Decisions',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Charity_Drive',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Visiting_Ours',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_In_God_We_Trust',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_My_Mother,_the_Car',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Storming_the_Castle',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Pier_Pressure',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Public_Relations',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Marta_Complex',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Beef_Consomm%C3%A9',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Shock_and_Aww',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Staff_Infection',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Altar_Egos',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Justice_Is_Blind',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Missing_Kitty',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Best_Man_for_the_Gob',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Whistler%27s_Mother',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Not_Without_My_Daughter',
                'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Let_%27Em_Eat_Cake']

season_2_urls = ['https://arresteddevelopment.fandom.com/wiki/Transcript_of_The_One_Where_Michael_Leaves',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_The_One_Where_They_Build_a_House',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_%C2%A1Amigos!',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Good_Grief',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Sad_Sack',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Afternoon_Delight',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Switch_Hitter',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Queen_for_a_Day',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Burning_Love',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Ready,_Aim,_Marry_Me',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Out_on_a_Limb',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Hand_to_God',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Motherboy_XXX',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_The_Immaculate_Election',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Sword_of_Destiny',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Meat_the_Veals',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Spring_Breakout',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Righteous_Brothers']

season_3_urls = ['https://arresteddevelopment.fandom.com/wiki/Transcript_of_The_Cabin_Show',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_For_British_Eyes_Only',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Forget-Me-Now',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Notapusy',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Mr._F',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_The_Ocean_Walker',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Prison_Break-In',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Making_a_Stand',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_S.O.B.s',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Fakin%27_It',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Family_Ties',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Exit_Strategy',
                 'https://arresteddevelopment.fandom.com/wiki/Transcript_of_Development_Arrested']

seasons = [season_1_urls, season_2_urls, season_3_urls]